### ISSUE TITLE
Newman not working with Node.js v0.12.0

### ISSUE THREAD

**Issue by msumberaz** [a85/Newman#183]
After just calling plain old `newman -c collection.json -e environment`

/usr/local/lib/node_modules/newman/node_modules/jsdom-nogyp/lib/jsdom/level1/core.js:554
      Array.prototype.splice.call(this._childNodes, refChildIndex, 0, newChild
                             ^
TypeError: Cannot set property length of [object Object] which has only a getter
    at Object.core.Node.insertBefore (/usr/local/lib/node_modules/newman/node_modules/jsdom-nogyp/lib/jsdom/level1/core.js:554:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/newman/node_modules/jsdom-nogyp/lib/jsdom/level2/events.js:314:20)
    at Object.proto.(anonymous function) [as insertBefore] (/usr/local/lib/node_modules/newman/node_modules/jsdom-nogyp/lib/jsdom/utils.js:23:26)
    at Object.core.Node.appendChild (/usr/local/lib/node_modules/newman/node_modules/jsdom-nogyp/lib/jsdom/level1/core.js:672:17)
    at /usr/local/lib/node_modules/newman/node_modules/jquery/dist/jquery.js:4006:18
    at /usr/local/lib/node_modules/newman/node_modules/jquery/dist/jquery.js:4026:3
    at module.exports (/usr/local/lib/node_modules/newman/node_modules/jquery/dist/jquery.js:31:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/newman/src/utilities/PreRequestScriptProcessor.js:6:48)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by abhijitkane** [comment]
This issue has been fixed in version 1.2.12 of Newman. Can you upgrade and confirm?

**Comment by msumberaz** [comment]
Updated and the error is gone. Thank you!
