### ISSUE TITLE
Error occasionally getting recieved by a recent change

### ISSUE THREAD

**Issue by wbrooks1981** [a85/Newman#194]
After upgrading to Newman 1.2.13, I noticed an error coming through.  This was random at times,  but I was getting the following:

TypeError: Cannot read property '0' of undefined
    at Object.jsface.Class._runTestCases (C:\Users\WBrooks\AppData\Roaming\npm\node_modules\newman\src\responseHandlers\TestResponseHandler.js:51:20)
    at Object.jsface.Class._onRequestExecuted (C:\Users\WBrooks\AppData\Roaming\npm\node_modules\newman\src\responseHandlers\TestResponseHandler.js:37:28)
    at EventEmitter.emit (events.js:117:20)
    at Object.jsface.Class.emit (C:\Users\WBrooks\AppData\Roaming\npm\node_modules\newman\src\utilities\EventEmitter.js:34:16)
    at Object.<anonymous> (C:\Users\WBrooks\AppData\Roaming\npm\node_modules\newman\src\runners\RequestRunner.js:189:22)
    at self.callback (C:\Users\WBrooks\AppData\Roaming\npm\node_modules\newman\node_modules\request\request.js:123:22)
    at Request.EventEmitter.emit (events.js:95:17)
    at ClientRequest.self.clientErrorHandler (C:\Users\WBrooks\AppData\Roaming\npm\node_modules\newman\node_modules\request\request.js:244:10)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at CleartextStream.socketErrorListener (http.js:1547:9)

After looking through the project the following piece of code is causing the issue in TestResponseHandler
if(body[0] === '\uFEFF') {
        //body = body.substring(1);
}
The check against the body object is failing. However, more importantly the piece of code doesn't do anything.  (I am not sure if this was left in there by mistake or for use in future development).

Anyway, when I change my local instance of newman and remove the code, my tests run completely.  Add it back in and the error will show up.

**Comment by abhijitkane** [comment]
It was added to handle ucs2-encoded responses, but then we added a command-line option to force a particular encoding. We'll remove this in the next release. Thanks for reporting this.

**Comment by wbrooks1981** [comment]
No problem and thanks.  I'll keep an eye out for the next release.

**Comment by wbrooks1981** [comment]
After the update today, it's working well.
